In [1]:
import numpy as np

## dataTypes $ attributes

# numpy is main ndarray

In [2]:
a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3],
           [4,5,6]])

In [6]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [8]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(4, 3)

In [12]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 2)

In [13]:
a1.dtype

dtype('int32')

In [14]:
a2.dtype

dtype('int32')

In [15]:
a1.size

3

In [16]:
a3.size

12

In [17]:
type(a1)

numpy.ndarray

In [18]:
# create  DATA frame

In [19]:
import pandas as pd

In [22]:
df=pd.DataFrame(a2)

In [23]:
df

0  1  2
0  1  2  3
1  4  5  6

# create numpy array

In [24]:
sample=np.array([1,2,3])

In [25]:
sample

array([1, 2, 3])

In [26]:
sample.dtype

dtype('int32')

In [27]:
ones=np.ones((2,3))

In [28]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
ones.dtype

dtype('float64')

In [30]:
type(ones)

numpy.ndarray

In [32]:
zeros=np.zeros((2,3))

In [33]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
range=np.arange(0,10,2)

In [35]:
range

array([0, 2, 4, 6, 8])

In [37]:
random=np.random.randint(0,10,size=(3,8))

random

In [38]:
random

array([[4, 0, 0, 0, 0, 4, 7, 4],
       [7, 1, 9, 7, 0, 7, 5, 8],
       [3, 1, 3, 6, 9, 7, 4, 9]])

In [39]:
random2=np.random.random((5,3))

In [40]:
random2

array([[0.6447504 , 0.14754536, 0.60620271],
       [0.02013526, 0.26668231, 0.34940291],
       [0.05240284, 0.53203276, 0.81945793],
       [0.57902409, 0.61532267, 0.3273918 ],
       [0.08150609, 0.86848249, 0.65828781]])

In [42]:
random2.shape

(5, 3)

In [43]:
random3=np.random.rand(5,3)

In [44]:
random3

array([[0.68046767, 0.59137326, 0.26114705],
       [0.92072139, 0.72759125, 0.83337551],
       [0.87937403, 0.16927946, 0.68051274],
       [0.24335948, 0.5727057 , 0.4471443 ],
       [0.63464368, 0.72880681, 0.63330209]])